Daps example
Digital-Ecosystems/edc-ionos-s3 pull request #20
Opened 2023-04-19 17:04 UTC by darashev-daiteap

Add file transfer push example with two connectors that are connecting to DAPS.

Tasks:
- [x] In **requirements** section add information about DNS, hostname, and IP addresses needed for the deployment.
- [x] Add wait time for the DNS of the just created container registry to resolve. This often times out currently, because it could take more time
- [x] Add a couple of sencences in the README about what the script **./deploy-services.sh** does
- [x] Automate the steps in README, so that parameters are extracted automatically from CURL responses and new requests are automatically generated
- [x] Add explaination of what each CURL requests does exactly
- [x] Add warning for number of S3 keys limit

2023-05-02 08:22 UTC, akafazov requested changes
Added tasks in the PR description which need to be done

2023-05-02 08:35 UTC, akafazov commented
Installation failed:

```sh

│ Warning: Helm release "edc-ionos-s3-consumer" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│ 
│   with helm_release.edc-ionos-s3-consumer,
│   on main.tf line 73, in resource "helm_release" "edc-ionos-s3-consumer":
│   73: resource "helm_release" "edc-ionos-s3-consumer" {
│ 
╵
╷
│ Warning: Helm release "edc-ionos-s3-provider" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│ 
│   with helm_release.edc-ionos-s3-provider,
│   on main.tf line 167, in resource "helm_release" "edc-ionos-s3-provider":
│  167: resource "helm_release" "edc-ionos-s3-provider" {
│ 
╵
╷
│ Error: timed out waiting for the condition
│ 
│   with helm_release.edc-ionos-s3-consumer,
│   on main.tf line 73, in resource "helm_release" "edc-ionos-s3-consumer":
│   73: resource "helm_release" "edc-ionos-s3-consumer" {
│ 
╵
╷
│ Error: timed out waiting for the condition
│ 
│   with helm_release.edc-ionos-s3-provider,
│   on main.tf line 167, in resource "helm_release" "edc-ionos-s3-provider":
│  167: resource "helm_release" "edc-ionos-s3-provider" {
│ 
╵
✘-1 ~/src/edc-ionos-s3/example/file-transfer-push-daps/terraform [daps-example ↑·1|✚ 3…13] $ 
```

2023-05-02 13:38 UTC, darashev-daiteap commented
> Installation failed:
> 
> ```shell
> │ Warning: Helm release "edc-ionos-s3-consumer" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
> │ 
> │   with helm_release.edc-ionos-s3-consumer,
> │   on main.tf line 73, in resource "helm_release" "edc-ionos-s3-consumer":
> │   73: resource "helm_release" "edc-ionos-s3-consumer" {
> │ 
> ╵
> ╷
> │ Warning: Helm release "edc-ionos-s3-provider" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
> │ 
> │   with helm_release.edc-ionos-s3-provider,
> │   on main.tf line 167, in resource "helm_release" "edc-ionos-s3-provider":
> │  167: resource "helm_release" "edc-ionos-s3-provider" {
> │ 
> ╵
> ╷
> │ Error: timed out waiting for the condition
> │ 
> │   with helm_release.edc-ionos-s3-consumer,
> │   on main.tf line 73, in resource "helm_release" "edc-ionos-s3-consumer":
> │   73: resource "helm_release" "edc-ionos-s3-consumer" {
> │ 
> ╵
> ╷
> │ Error: timed out waiting for the condition
> │ 
> │   with helm_release.edc-ionos-s3-provider,
> │   on main.tf line 167, in resource "helm_release" "edc-ionos-s3-provider":
> │  167: resource "helm_release" "edc-ionos-s3-provider" {
> │ 
> ╵
> ✘-1 ~/src/edc-ionos-s3/example/file-transfer-push-daps/terraform [daps-example ↑·1|✚ 3…13] $ 
> ```
Can you show the logs from the connector containers?

2023-05-03 06:30 UTC, akafazov commented
> 
> Can you show the logs from the connector containers?

The cluster is already deleted

2023-05-03 06:33 UTC, darashev-daiteap commented
>  Add wait time for the DNS of the just created container registry to resolve. This often times out currently, because it could take more time
 
 https://github.com/Digital-Ecosystems/edc-ionos-s3/blob/f5670f9aa5b0fc82d7460b493876e354c575cee6/example/file-transfer-push-daps/terraform/build-and-push-docker-images/main.tf#L70-L83

2023-05-03 06:46 UTC, akafazov commented
> > Add wait time for the DNS of the just created container registry to resolve. This often times out currently, because it could take more time
> 
> https://github.com/Digital-Ecosystems/edc-ionos-s3/blob/f5670f9aa5b0fc82d7460b493876e354c575cee6/example/file-transfer-push-daps/terraform/build-and-push-docker-images/main.tf#L70-L83

I know, but this needs to be increased

2023-05-03 14:23 UTC, akafazov requested changes

2023-05-03 14:23 UTC, akafazov commented on example/file-transfer-push-daps/README.md
> +We will have to call some URL's in order to transfer the file:
We need better explanation than this. What does the call do?

2023-05-03 14:23 UTC, akafazov commented on example/file-transfer-push-daps/README.md
> +curl --location --request POST "http://$CONSUMER_ADDRESS:8182/api/v1/management/contractnegotiations" \
Explain what does the request do?

2023-05-03 14:23 UTC, akafazov commented on example/file-transfer-push-daps/README.md
> +curl -X GET -H 'X-Api-Key: password' "http://$CONSUMER_ADDRESS:8182/api/v1/management/contractnegotiations/<ID>"
Same here

2023-05-03 14:23 UTC, akafazov commented on example/file-transfer-push-daps/README.md
> +curl --location --request POST "http://$CONSUMER_ADDRESS:8182/api/v1/management/transferprocess" \
description...

2023-05-04 10:16 UTC, merged